name: Typst Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: rust-lang/rustup-action@v1
        with:
          toolchain: stable

      - name: Install Typst via cargo
        run: |
          set -euo pipefail
          # Install typst with cargo (reliable and avoids parsing release asset names)
          cargo install --locked typst
          echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

      - name: Verify Typst is available
        run: |
          set -euo pipefail
          echo "PATH=$PATH"
          typst --version

      - name: Compile Typst documents
        run: |
          set -euo pipefail
          mkdir -p build
          # Find all .typ files (ignore .git) and compile each to build/<basename>.pdf
          find . -type f -name '*.typ' -not -path './.git/*' -not -path './node_modules/*' -print0 | while IFS= read -r -d '' file; do
            out="build/$(basename "${file}" .typ).pdf"
            echo "Compiling ${file} -> ${out}"
            typst compile "${file}" "${out}"
          done

      - name: Upload compiled PDFs
        uses: actions/upload-artifact@v4
        with:
          name: typst-compiled-pdfs
          path: build/*.pdf